---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

    # Podman Quadlets defaults
    podman_quadlets_base_dir: "{{ ansible_user_dir }}/.config/containers/systemd"
    podman_quadlets_auto_update: "registry"

    # Common labels for all containers
    podman_quadlets_common_labels:
      managed_by: "ansible"
      collection: "community.podman_quadlets"

    # Default timezone
    default_timezone: "Europe/Berlin"

  children:
    container_hosts:
      hosts:
        localhost:
          ansible_connection: local

        podman-host-1:
          ansible_host: 10.10.10.100
          ansible_user: podman

        podman-host-2:
          ansible_host: 10.10.10.101
          ansible_user: podman

      vars:
        # Container host specific settings
        podman_quadlets_cleanup_on_failure: true
        podman_quadlets_log_driver: "journald"
